version: '3'

services:
  recipe-backend:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      NODE_ENV: prod
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      MONGO_DB: recipe-db
    depends_on:
      - mongo
    command: node ./src/app.js

  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db